language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - wget "https://drive.google.com/file/d/0B5MzpY9kBtDVOTVnU3NIaUdySFE/edit"
# command to run tests
script: python realtime_facenet.py